### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ObscureCode** [JavaProphet/AvunaNoSQL#2]
Hi, I was wondering if you could stop programming Java. I was told by my good friend Looka that you're still writing POOP. I recommend taking a class on OOP. It's really useful and fun. Together we can create a better planet using Java.

Things to improve:
1) This repo
2) Every fucking thing in this fucking repo
3) Close every fucking account you own and kill yourself.
4) I'm just kidding.
5) I'm not.

![image](https://cloud.githubusercontent.com/assets/3393915/7350074/2ba1ce0a-ecf5-11e4-941b-117271747aab.png)

**Comment by ObscureCode** [comment]
Thanks for raising this to my attention, I'll be sure to watch out for 'Avuna NoSQL' in the future as it looks really promising and stuff. Yeah.. ermm.. yeah. No.

**Comment by JavaProphet** [comment]
You mad bro? If I had a portfolio of envious coders, I'd put you at the bottom. :)

**Comment by ObscureCode** [comment]
At least I do more than one language and don't try re-invent the wheel on every project I do because I lack inspiration or creativity. For someone who does a lot of Java, you still don't use conventions much.

Stop being so envious of me, it's OK.
The minute you stop this CLI shit and do something sexy and useful w/ a GUI, I'll stop ripping on everything you do. But until that day comes, stay consoley.
